---
- name: Create a CloudFormaton stack
  cloudformation:
    profile: "{{ profile }}"
    stack_name: "{{ stack_name }}"
    state: "present"
    region: "{{ region }}"
    disable_rollback: true
    template: "{{ template }}"
    template_parameters: "{{ template_parameters }}"
    tags:
      stack_name: "{{ stack_name }}"
